### ISSUE TITLE
Add e2e tests and actions

### ISSUE THREAD

**Issue by kalapyha** [kalapyha/solitaire-group-9#2]
Here's an example of how you could add Cypress to an existing React project and run tests using GitHub Actions:

- [x] First, you will need to install Cypress by running npm install cypress or yarn add cypress in your project.
- [x] Next, you will need to add Cypress commands to your project's package.json file, such as "cy:open": "cypress open" and "cy:run": "cypress run"

- [x] Create a new directory in your project called cypress and add a new file called cypress.json to configure Cypress.

- [x] Now you can open Cypress by running npm run cy:open or yarn cy:open

- [x] Once Cypress is open you can start writing your tests.

- [x] To run tests using GitHub Actions, you will need to create a new workflow in your project's .github/workflows directory. Here's an example workflow that runs tests using Cypress:

```
name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Run Cypress tests
      run: npm run cy:run
```

This workflow will run Cypress tests on the main branch every time you push to it.
